CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    legal_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'MEMBER'))
);

CREATE TABLE trademark_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    mark_name VARCHAR(500) NOT NULL,
    mark_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    status_detail TEXT,
    agency_id BIGINT REFERENCES agencies(id),
    note TEXT,
    data_origin VARCHAR(30) NOT NULL,
    verification_status VARCHAR(30) NOT NULL,
    verification_note TEXT,
    created_by BIGINT REFERENCES users(id),
    updated_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT trademark_records_mark_type_check CHECK (mark_type IN ('LOGO', 'TEXT', 'VISUAL', 'TEXT_LOGO', 'LOGO_TEXT', 'LOGO_TEXT_TAGLINE')),
    CONSTRAINT trademark_records_status_check CHECK (status IN ('GRANTED', 'EXPIRED', 'PENDING', 'REJECTED')),
    CONSTRAINT trademark_records_origin_check CHECK (data_origin IN ('IMPORTED', 'MANUAL')),
    CONSTRAINT trademark_records_verification_check CHECK (verification_status IN ('VERIFIED', 'NEEDS_REVIEW', 'UNVERIFIED'))
);

CREATE TABLE trademark_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trademark_record_id BIGINT NOT NULL REFERENCES trademark_records(id),
    application_no VARCHAR(150) NOT NULL,
    filed_date DATE,
    raw_filed_date VARCHAR(150),
    jurisdiction_code VARCHAR(10) NOT NULL DEFAULT 'VN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE trademark_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES trademark_applications(id),
    certificate_no VARCHAR(150),
    issue_date DATE,
    expiry_date DATE,
    raw_expiry_date VARCHAR(150),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE nice_classes (
    class_no INTEGER PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE trademark_record_classes (
    trademark_record_id BIGINT NOT NULL REFERENCES trademark_records(id),
    class_no INTEGER NOT NULL REFERENCES nice_classes(class_no),
    PRIMARY KEY (trademark_record_id, class_no)
);

CREATE TABLE trademark_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trademark_record_id BIGINT NOT NULL REFERENCES trademark_records(id),
    file_kind VARCHAR(30) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT trademark_files_kind_check CHECK (file_kind IN ('LOGO', 'DOCUMENT', 'OTHER'))
);

CREATE TABLE trademark_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trademark_record_id BIGINT NOT NULL REFERENCES trademark_records(id),
    from_status VARCHAR(50),
    to_status VARCHAR(50) NOT NULL,
    detail TEXT,
    effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    changed_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_trademark_records_company ON trademark_records(company_id);
CREATE INDEX idx_trademark_records_status ON trademark_records(status);
CREATE INDEX idx_trademark_records_agency ON trademark_records(agency_id);
CREATE INDEX idx_trademark_applications_record ON trademark_applications(trademark_record_id);
CREATE INDEX idx_trademark_certificates_application ON trademark_certificates(application_id);
CREATE INDEX idx_status_history_record_effective ON trademark_status_history(trademark_record_id, effective_at DESC);

INSERT INTO companies (code, legal_name, created_at, updated_at) VALUES
    ('TNHH', 'CTY TNHH An Thái', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SGAT', 'CTY CP Sài Gòn An Thái', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DTPT', 'CTY CP ĐT & PT An Thái', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SXTM', 'CTY CP SX TM An Thái Việt Nam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO nice_classes (class_no, name) VALUES
    (11, 'Nhóm 11'), (29, 'Nhóm 29'), (30, 'Nhóm 30'), (31, 'Nhóm 31'),
    (32, 'Nhóm 32'), (35, 'Nhóm 35'), (36, 'Nhóm 36'), (39, 'Nhóm 39'),
    (43, 'Nhóm 43');
